# Generated by Django 3.2.2 on 2021-05-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_query',
            field=models.CharField(max_length=6),
        ),
    ]
